# Site settings
author: Emery Kurt
title: Makeup in Tech
header-img: img/home-bg.png
email: emerylumsden@gmail.com
copyright_name: Emery Kurt
description: > # this means to ignore newlines until "baseurl:"
  The comprehensive life of a Makeup Artist gone Tech.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  emerykurt

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
